# Pytorch Basics

In [1]:
import torch

`Tensor` is a data structure which is a fundamental building block of PyTorch. Tensors are pretty much like numpy arrays, except that unlike numpy, tensors are designed to take advantage of parallel computation capabilities of a GPU. A lot of Tensor syntax is similar to that of numpy arrays.

pytorch supports multiple typing formats

* 32-bit floating point,
* 64-bit floating point,
* 64-bit complex,
* 128-bit complex,
* 16-bit floating point 1,
* 16-bit floating point 2 (bfloat16),
* 8-bit integer (unsigned),
* 8-bit integer (signed),
* 16-bit integer (signed),
* 32-bit integer (signed),
* 64-bit integer (signed),
* Boolean

In [2]:
o = torch.arange(15).view(-1, 5)
o

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [3]:
o.shape

torch.Size([3, 5])

In [4]:
o.ndim

2

In [5]:
o.dtype

torch.int64

In [6]:
o.size()

torch.Size([3, 5])

## Pytorch tensor creation can be done as simple as

In [7]:
torch.tensor([0, 1, 2, 3, 4])

tensor([0, 1, 2, 3, 4])

In [8]:
torch.tensor(range(5))

tensor([0, 1, 2, 3, 4])

We can also specify the data type of the tensor using the `dtype` argument and specifying the datatype

In [9]:
torch.tensor(range(5), dtype=torch.float32)

tensor([0., 1., 2., 3., 4.])

The same can be done with pytorch using 

In [10]:
torch.arange(5)

tensor([0, 1, 2, 3, 4])

The same way when we want to generate n array elements between limits with equal spacing that is also possible

_here lets generate 10 numbers between 1 and 5 inclusively_

In [11]:
torch.linspace(1, 5, 10)

tensor([1.0000, 1.4444, 1.8889, 2.3333, 2.7778, 3.2222, 3.6667, 4.1111, 4.5556,
        5.0000])

randn function creates a random array of normal distribution

In [12]:
torch.randn(5)

tensor([-0.9508, -0.5521,  0.7906,  0.5275, -0.1951])

## Pytorch Numerical Operations 
Scalar x Scaler operations

In [13]:
a, b = torch.tensor(1), torch.tensor(2)

In [14]:
a + b

tensor(3)

In [15]:
a - b

tensor(-1)

In [16]:
a * b

tensor(2)

Whenever there is a division operation there is a type casting done and all elements are converted to float dtype

In [17]:
a / b

tensor(0.5000)

Vector Vector operations

In [18]:
a, b = torch.tensor([1, 2, 3]), torch.tensor([4, 5, 6])
a, b

(tensor([1, 2, 3]), tensor([4, 5, 6]))

and the same follows for vector vector operations

In [19]:
a + b

tensor([5, 7, 9])

## Broadcasting

When operating on two arrays, pytorch compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimensions and works its way left. Two dimensions are compatible when

1. they are equal.
2. one of them is a scaler

In [20]:
a, b = torch.arange(5), torch.tensor(5)
a, b

(tensor([0, 1, 2, 3, 4]), tensor(5))

here the scaler object `b` is broadcasted to the shape of a and the element wise addition takes place

In [21]:
a + b

tensor([5, 6, 7, 8, 9])

#### to replicate the same semantics in pytorch

In [22]:
b.expand_as(a)

tensor([5, 5, 5, 5, 5])

In [23]:
assert torch.all(a + b.expand_as(a) == b + a)

### _the same happens with any vector and matrix or any higher rank tensor_

In [24]:
a, b = torch.arange(5), torch.arange(15).view(3, 5)
a.shape, b.shape

(torch.Size([5]), torch.Size([3, 5]))

In [25]:
a

tensor([0, 1, 2, 3, 4])

In [26]:
b

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [27]:
a + b

tensor([[ 0,  2,  4,  6,  8],
        [ 5,  7,  9, 11, 13],
        [10, 12, 14, 16, 18]])

## pytorch matrix basics

In [28]:
a, b = torch.arange(9).view(3, 3), torch.arange(9).view(3, 3)

In [29]:
a

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [30]:
torch.transpose(a, 0, 1)

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])

In [31]:
a.T

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])

element wise addition

In [32]:
a + b

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

element wise subtraction

In [33]:
a - b

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

element wise multiplication

In [34]:
a * b

tensor([[ 0,  1,  4],
        [ 9, 16, 25],
        [36, 49, 64]])

## Matrix Multiplication

lets have a general idea of matrix multiplication implemented in plain pytorch and see how pytorch helps in speeding up processes

for a more visual introduction to matrix multiplication you can visit the following site

[http://matrixmultiplication.xyz](http://matrixmultiplication.xyz)

here we will implement a matrix multiplication operation in pytorch



In [35]:
def matmul(a,b):
    ar,ac = a.shape # n_rows * n_cols
    br,bc = b.shape
    assert ac==br
    c = torch.zeros(ar, bc)
    for i in range(ar):
        for j in range(bc):
            for k in range(ac): # or br
                c[i,j] += a[i,k] * b[k,j]
    return c

In [36]:
matmul(a, b)

tensor([[ 15.,  18.,  21.],
        [ 42.,  54.,  66.],
        [ 69.,  90., 111.]])

In [37]:
torch.matmul(a, b)

tensor([[ 15,  18,  21],
        [ 42,  54,  66],
        [ 69,  90, 111]])

#### Here we can clearly see how efficient pytorch speeds up the code than the naive implementation of matrix multiplication

which is 10 times faster and the difference is even outstanding when the matrix is even larger

In [38]:
%time matmul(a, b)

CPU times: user 2.61 ms, sys: 0 ns, total: 2.61 ms
Wall time: 1.54 ms


tensor([[ 15.,  18.,  21.],
        [ 42.,  54.,  66.],
        [ 69.,  90., 111.]])

In [39]:
%time torch.matmul(a, b)

CPU times: user 469 µs, sys: 81 µs, total: 550 µs
Wall time: 334 µs


tensor([[ 15,  18,  21],
        [ 42,  54,  66],
        [ 69,  90, 111]])

In [40]:
a, b = torch.randn((100, 100)), torch.randn((100, 100))
a, b

(tensor([[ 0.3153,  0.5802,  0.3383,  ...,  0.2394, -0.4644, -1.5382],
         [-0.1452, -0.0397,  1.2485,  ..., -2.0340, -0.1912, -0.2951],
         [-0.2093,  0.6722,  0.7600,  ..., -0.5073, -0.5701, -0.4510],
         ...,
         [-0.6028, -0.1526,  1.0884,  ...,  0.6191,  1.4685,  0.5394],
         [ 0.1944,  1.2033,  0.0027,  ..., -0.6841, -0.1462,  2.6923],
         [ 1.8873, -0.1093,  2.1244,  ...,  0.4125, -0.9614,  0.1285]]),
 tensor([[-5.6842e-01, -7.3672e-01, -8.8033e-01,  ..., -1.7469e+00,
           5.7359e-01,  1.7447e+00],
         [ 2.9228e-01, -9.1400e-01, -1.8254e+00,  ...,  2.5205e+00,
           1.5210e+00, -9.7875e-02],
         [ 1.1219e+00, -1.1103e+00,  1.9019e+00,  ..., -1.4688e+00,
          -2.3237e-01, -1.3193e+00],
         ...,
         [ 2.6275e-01,  8.1490e-02,  4.0630e-01,  ..., -7.3608e-01,
          -1.1049e+00,  1.2033e-03],
         [-3.0043e-01, -3.7975e-01,  3.8867e-01,  ...,  1.1476e+00,
           1.2454e+00,  1.0126e+00],
         [-1.8141e+

In [41]:
%time matmul(a, b)

CPU times: user 14.5 s, sys: 0 ns, total: 14.5 s
Wall time: 14.4 s


tensor([[ -3.1089,  -8.3611,   4.8300,  ...,  -0.5223,   4.0254,   4.7235],
        [ -1.6580,  -4.9681,  -8.1235,  ...,  -3.4308,  -3.5327, -16.9937],
        [ -8.4278,   2.8213,   1.5050,  ...,   2.6268,  -9.2838,   5.7993],
        ...,
        [ 12.4939,  -4.3958,   3.4316,  ...,   5.0737,   3.5505, -12.9952],
        [  4.6384,  17.4723,  10.9148,  ...,   4.4103,   8.2617,   1.4136],
        [  5.5554,   3.7100,  -3.0954,  ...,  -7.1114,  -1.4777,   0.1326]])

In [42]:
%time torch.matmul(a, b)

CPU times: user 1.63 ms, sys: 0 ns, total: 1.63 ms
Wall time: 618 µs


tensor([[ -3.1089,  -8.3611,   4.8300,  ...,  -0.5223,   4.0254,   4.7235],
        [ -1.6580,  -4.9681,  -8.1235,  ...,  -3.4308,  -3.5327, -16.9937],
        [ -8.4278,   2.8213,   1.5050,  ...,   2.6268,  -9.2838,   5.7993],
        ...,
        [ 12.4939,  -4.3958,   3.4316,  ...,   5.0737,   3.5505, -12.9952],
        [  4.6384,  17.4723,  10.9148,  ...,   4.4103,   8.2617,   1.4136],
        [  5.5554,   3.7100,  -3.0954,  ...,  -7.1114,  -1.4777,   0.1326]])

there is also a shortcut to doing matrix multiplication the same way as we do `+`, `-`, `x`, `÷`

In [43]:
a, b = torch.arange(4).view(2, 2), torch.arange(4).view(2, 2)

In [44]:
a @ b

tensor([[ 2,  3],
        [ 6, 11]])

## Pytorch views

PyTorch allows a tensor to be a View of an existing tensor. View tensor shares the same underlying data with its base tensor. Supporting View avoids explicit data copy, thus allows us to do fast and memory efficient reshaping, slicing and element-wise operations.

In [45]:
a = torch.arange(25)
a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])

In [48]:
a.view(-1, 25).shape

torch.Size([1, 25])

In [49]:
a.view(5, 5)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])